import {
    ACCREDITATIONS,
    APPROVAL_BODIES,
    CONTENT_STATUS,
    COURSE_LEVELS,
    ENTITY_STATUS,
    EXAM_CATEGORIES,
    EXAM_LEVELS,
    EXAM_MODES,
    LEAD_PRIORITIES,
    LEAD_SOURCES,
    LEAD_STATUSES,
    MODERATION_STATUSES,
    OWNERSHIP_TYPES,
    RESOURCE_TYPES,
    STUDY_MODES,
    THEME_COLORS,
    TRENDING_CATEGORIES,
} from './constants';
import { ROLES } from './permissions';
import type { Permission } from './permissions';
import type { HtmlPolicy } from '@/lib/html/policy';

export type AdminFieldType =
    | 'text'
    | 'textarea'
    | 'richtext'
    | 'number'
    | 'boolean'
    | 'select'
    | 'multiselect'
    | 'date'
    | 'datetime'
    | 'slug'
    | 'reference'
    | 'tags'
    | 'json'
    | 'image';

export interface AdminField {
    name: string;
    label: string;
    type: AdminFieldType;
    required?: boolean;
    options?: readonly string[];
    /** Model name for reference pickers, e.g. 'College'. */
    refModel?: string;
    refLabelField?: string;
    help?: string;
    placeholder?: string;
    min?: number;
    max?: number;
    step?: number;
    group?: string;
    /** Hide from the create/edit form (read-only computed fields). */
    readOnly?: boolean;
    colSpan?: 1 | 2;
    /**
     * Sanitisation allow-list for `richtext` fields. Defaults to `web`, which
     * matches the `.prose-sathi` stylesheet. Use `email` where inline styles and
     * layout tables must survive, because email clients ignore stylesheets.
     */
    htmlPolicy?: HtmlPolicy;
}

export interface AdminColumn {
    name: string;
    label: string;
    type?: 'text' | 'badge' | 'number' | 'date' | 'currency' | 'boolean';
    width?: string;
}

export interface AdminResource {
    key: string;
    model: string;
    label: string;
    labelSingular: string;
    icon: string;
    description: string;
    /** Field used as the human-readable title in lists and audit logs. */
    titleField: string;
    slugField?: string;
    searchFields: string[];
    defaultSort: Record<string, 1 | -1>;
    columns: AdminColumn[];
    fields: AdminField[];
    permissions: {
        read: Permission;
        create: Permission;
        update: Permission;
        delete: Permission;
    };
    /** Public URL builder for the "view live" link. */
    publicPath?: (doc: Record<string, unknown>) => string;
    softDelete?: boolean;
    revalidateTags?: string[];
}

const statusField: AdminField = {
    name: 'status',
    label: 'Status',
    type: 'select',
    options: CONTENT_STATUS,
    required: true,
    group: 'Publishing',
};

const entityStatusField: AdminField = {
    name: 'status',
    label: 'Status',
    type: 'select',
    options: ENTITY_STATUS,
    required: true,
    group: 'Publishing',
};

const seoFields: AdminField[] = [
    { name: 'seo.title', label: 'SEO title', type: 'text', group: 'SEO', colSpan: 2 },
    { name: 'seo.description', label: 'Meta description', type: 'textarea', group: 'SEO', colSpan: 2 },
    { name: 'seo.keywords', label: 'Keywords', type: 'tags', group: 'SEO', colSpan: 2 },
    { name: 'seo.noIndex', label: 'Exclude from search engines', type: 'boolean', group: 'SEO' },
];

export const ADMIN_RESOURCES: Record<string, AdminResource> = {
    colleges: {
        key: 'colleges',
        model: 'College',
        label: 'Colleges',
        labelSingular: 'College',
        icon: 'Building2',
        description: 'Institute profiles, fees, placements, approvals and publishing state.',
        titleField: 'name',
        slugField: 'slug',
        searchFields: ['name', 'shortName', 'cityName', 'stateName'],
        defaultSort: { updatedAt: -1 },
        softDelete: true,
        revalidateTags: ['colleges'],
        publicPath: (doc) => `/colleges/${doc.slug as string}`,
        permissions: {
            read: 'college.read',
            create: 'college.create',
            update: 'college.update',
            delete: 'college.delete',
        },
        columns: [
            { name: 'name', label: 'College' },
            { name: 'cityName', label: 'City' },
            { name: 'ownership', label: 'Ownership', type: 'badge' },
            { name: 'feeRange.min', label: 'Fee from', type: 'currency' },
            { name: 'rating.overall', label: 'Rating', type: 'number' },
            { name: 'status', label: 'Status', type: 'badge' },
            { name: 'updatedAt', label: 'Updated', type: 'date' },
        ],
        fields: [
            { name: 'name', label: 'College name', type: 'text', required: true, group: 'Basics', colSpan: 2 },
            { name: 'slug', label: 'Slug', type: 'slug', required: true, group: 'Basics' },
            { name: 'shortName', label: 'Short name', type: 'text', group: 'Basics' },
            { name: 'tagline', label: 'Tagline', type: 'text', group: 'Basics', colSpan: 2 },
            { name: 'description', label: 'Short description', type: 'textarea', group: 'Basics', colSpan: 2 },
            { name: 'overviewHtml', label: 'Overview', type: 'richtext', group: 'Content', colSpan: 2 },
            { name: 'state', label: 'State', type: 'reference', refModel: 'State', refLabelField: 'name', required: true, group: 'Location' },
            { name: 'city', label: 'City', type: 'reference', refModel: 'City', refLabelField: 'name', required: true, group: 'Location' },
            { name: 'address', label: 'Address', type: 'textarea', group: 'Location', colSpan: 2 },
            { name: 'ownership', label: 'Ownership', type: 'select', options: OWNERSHIP_TYPES, required: true, group: 'Profile' },
            { name: 'establishedYear', label: 'Established year', type: 'number', min: 1800, max: 2100, group: 'Profile' },
            { name: 'affiliatedTo', label: 'Affiliated to', type: 'text', group: 'Profile', colSpan: 2 },
            { name: 'approvals', label: 'Approvals', type: 'multiselect', options: APPROVAL_BODIES, group: 'Profile' },
            { name: 'accreditation', label: 'Accreditation', type: 'multiselect', options: ACCREDITATIONS, group: 'Profile' },
            { name: 'campusSizeAcres', label: 'Campus size (acres)', type: 'number', group: 'Profile' },
            { name: 'totalStudents', label: 'Total students', type: 'number', group: 'Profile' },
            { name: 'feeRange.min', label: 'Annual fee from (₹)', type: 'number', group: 'Fees' },
            { name: 'feeRange.max', label: 'Annual fee up to (₹)', type: 'number', group: 'Fees' },
            { name: 'hostelAvailable', label: 'Hostel available', type: 'boolean', group: 'Fees' },
            { name: 'ranking.nirfOverall', label: 'NIRF overall rank', type: 'number', group: 'Ranking' },
            { name: 'ranking.nirfCategory', label: 'NIRF category rank', type: 'number', group: 'Ranking' },
            { name: 'ranking.nirfCategoryName', label: 'NIRF category', type: 'text', group: 'Ranking' },
            { name: 'placement.highestPackage', label: 'Highest package (₹)', type: 'number', group: 'Placements' },
            { name: 'placement.averagePackage', label: 'Average package (₹)', type: 'number', group: 'Placements' },
            { name: 'placement.placementPercentage', label: 'Placement rate (%)', type: 'number', min: 0, max: 100, group: 'Placements' },
            { name: 'placement.topRecruiters', label: 'Top recruiters', type: 'tags', group: 'Placements', colSpan: 2 },
            { name: 'facilities', label: 'Facilities', type: 'tags', group: 'Campus', colSpan: 2 },
            { name: 'admissionsHtml', label: 'Admission process', type: 'richtext', group: 'Content', colSpan: 2 },
            { name: 'eligibilityHtml', label: 'Eligibility', type: 'richtext', group: 'Content', colSpan: 2 },
            { name: 'contact.phone', label: 'Phone', type: 'text', group: 'Contact' },
            { name: 'contact.email', label: 'Email', type: 'text', group: 'Contact' },
            { name: 'contact.website', label: 'Website', type: 'text', group: 'Contact', colSpan: 2 },
            { name: 'brochureUrl', label: 'Brochure URL', type: 'text', group: 'Contact', colSpan: 2 },
            { name: 'isFeatured', label: 'Featured', type: 'boolean', group: 'Publishing' },
            { name: 'isVerified', label: 'Verified', type: 'boolean', group: 'Publishing' },
            { name: 'displayOrder', label: 'Display order', type: 'number', group: 'Publishing' },
            { name: 'dataSourceNote', label: 'Data source note', type: 'textarea', group: 'Publishing', colSpan: 2 },
            statusField,
            ...seoFields,
        ],
    },

    courses: {
        key: 'courses',
        model: 'Course',
        label: 'Courses',
        labelSingular: 'Course',
        icon: 'GraduationCap',
        description: 'Programme definitions, eligibility, fees and career content.',
        titleField: 'name',
        slugField: 'slug',
        searchFields: ['name', 'shortName', 'categoryName'],
        defaultSort: { displayOrder: 1 },
        softDelete: true,
        revalidateTags: ['courses'],
        publicPath: (doc) => `/courses/${doc.slug as string}`,
        permissions: {
            read: 'course.read',
            create: 'course.manage',
            update: 'course.manage',
            delete: 'course.manage',
        },
        columns: [
            { name: 'name', label: 'Course' },
            { name: 'categoryName', label: 'Category' },
            { name: 'level', label: 'Level', type: 'badge' },
            { name: 'durationLabel', label: 'Duration' },
            { name: 'collegeCount', label: 'Colleges', type: 'number' },
            { name: 'status', label: 'Status', type: 'badge' },
        ],
        fields: [
            { name: 'name', label: 'Course name', type: 'text', required: true, group: 'Basics', colSpan: 2 },
            { name: 'slug', label: 'Slug', type: 'slug', required: true, group: 'Basics' },
            { name: 'shortName', label: 'Short name', type: 'text', group: 'Basics' },
            { name: 'category', label: 'Category', type: 'reference', refModel: 'CourseCategory', refLabelField: 'name', required: true, group: 'Basics' },
            { name: 'level', label: 'Level', type: 'select', options: COURSE_LEVELS, required: true, group: 'Basics' },
            { name: 'durationMonths', label: 'Duration (months)', type: 'number', required: true, min: 1, max: 120, group: 'Basics' },
            { name: 'durationLabel', label: 'Duration label', type: 'text', required: true, group: 'Basics' },
            { name: 'studyModes', label: 'Study modes', type: 'multiselect', options: STUDY_MODES, group: 'Basics' },
            { name: 'overview', label: 'Overview', type: 'richtext', group: 'Content', colSpan: 2 },
            { name: 'eligibility', label: 'Eligibility', type: 'richtext', group: 'Content', colSpan: 2 },
            { name: 'admissionProcess', label: 'Admission process', type: 'richtext', group: 'Content', colSpan: 2 },
            { name: 'syllabusHtml', label: 'Syllabus', type: 'richtext', group: 'Content', colSpan: 2 },
            { name: 'careerHtml', label: 'Career & scope', type: 'richtext', group: 'Content', colSpan: 2 },
            { name: 'averageFee.min', label: 'Average fee from (₹)', type: 'number', group: 'Fees & salary' },
            { name: 'averageFee.max', label: 'Average fee up to (₹)', type: 'number', group: 'Fees & salary' },
            { name: 'averageSalary.min', label: 'Starting salary (₹)', type: 'number', group: 'Fees & salary' },
            { name: 'averageSalary.max', label: 'Experienced salary (₹)', type: 'number', group: 'Fees & salary' },
            { name: 'jobRoles', label: 'Job roles', type: 'tags', group: 'Career', colSpan: 2 },
            { name: 'skills', label: 'Skills', type: 'tags', group: 'Career', colSpan: 2 },
            { name: 'topRecruiters', label: 'Top recruiters', type: 'tags', group: 'Career', colSpan: 2 },
            { name: 'isFeatured', label: 'Featured', type: 'boolean', group: 'Publishing' },
            { name: 'displayOrder', label: 'Display order', type: 'number', group: 'Publishing' },
            statusField,
            ...seoFields,
        ],
    },

    'course-categories': {
        key: 'course-categories',
        model: 'CourseCategory',
        label: 'Course categories',
        labelSingular: 'Course category',
        icon: 'LayoutGrid',
        description: 'Homepage streams: icons, captions, ordering and featured state.',
        titleField: 'name',
        slugField: 'slug',
        searchFields: ['name', 'shortName'],
        defaultSort: { displayOrder: 1 },
        revalidateTags: ['course-categories', 'homepage'],
        publicPath: (doc) => `/courses/category/${doc.slug as string}`,
        permissions: {
            read: 'course.read',
            create: 'course.manage',
            update: 'course.manage',
            delete: 'course.manage',
        },
        columns: [
            { name: 'name', label: 'Category' },
            { name: 'subtitle', label: 'Caption' },
            { name: 'courseCount', label: 'Courses', type: 'number' },
            { name: 'collegeCount', label: 'Colleges', type: 'number' },
            { name: 'isFeatured', label: 'Featured', type: 'boolean' },
            { name: 'displayOrder', label: 'Order', type: 'number' },
        ],
        fields: [
            { name: 'name', label: 'Name', type: 'text', required: true, group: 'Basics' },
            { name: 'slug', label: 'Slug', type: 'slug', required: true, group: 'Basics' },
            { name: 'shortName', label: 'Short name', type: 'text', group: 'Basics' },
            { name: 'subtitle', label: 'Homepage caption', type: 'text', group: 'Basics', help: 'e.g. "B.Tech, M.Tech & More"' },
            { name: 'icon', label: 'Icon name', type: 'text', required: true, group: 'Appearance', help: 'Lucide icon, e.g. Cog' },
            { name: 'themeColor', label: 'Theme colour', type: 'select', options: THEME_COLORS, group: 'Appearance' },
            { name: 'description', label: 'Description', type: 'textarea', group: 'Basics', colSpan: 2 },
            { name: 'isFeatured', label: 'Show on homepage', type: 'boolean', group: 'Publishing' },
            { name: 'displayOrder', label: 'Display order', type: 'number', group: 'Publishing' },
            entityStatusField,
            ...seoFields,
        ],
    },

    specializations: {
        key: 'specializations',
        model: 'Specialization',
        label: 'Specializations',
        labelSingular: 'Specialization',
        icon: 'ListChecks',
        description: 'Course specialisations with scope and salary notes.',
        titleField: 'name',
        slugField: 'slug',
        searchFields: ['name', 'courseName'],
        defaultSort: { courseName: 1, displayOrder: 1 },
        revalidateTags: ['courses'],
        permissions: {
            read: 'course.read',
            create: 'specialization.manage',
            update: 'specialization.manage',
            delete: 'specialization.manage',
        },
        columns: [
            { name: 'name', label: 'Specialization' },
            { name: 'courseName', label: 'Course' },
            { name: 'collegeCount', label: 'Colleges', type: 'number' },
            { name: 'status', label: 'Status', type: 'badge' },
        ],
        fields: [
            { name: 'name', label: 'Name', type: 'text', required: true, group: 'Basics', colSpan: 2 },
            { name: 'slug', label: 'Slug', type: 'slug', required: true, group: 'Basics' },
            { name: 'course', label: 'Course', type: 'reference', refModel: 'Course', refLabelField: 'name', required: true, group: 'Basics' },
            { name: 'description', label: 'Description', type: 'textarea', group: 'Basics', colSpan: 2 },
            { name: 'careerScope', label: 'Career scope', type: 'textarea', group: 'Career', colSpan: 2 },
            { name: 'averageSalary.min', label: 'Salary from (₹)', type: 'number', group: 'Career' },
            { name: 'averageSalary.max', label: 'Salary up to (₹)', type: 'number', group: 'Career' },
            { name: 'displayOrder', label: 'Display order', type: 'number', group: 'Publishing' },
            entityStatusField,
        ],
    },

    exams: {
        key: 'exams',
        model: 'Exam',
        label: 'Exams',
        labelSingular: 'Exam',
        icon: 'FileText',
        description: 'Entrance exams with dates, pattern, syllabus and counselling content.',
        titleField: 'shortName',
        slugField: 'slug',
        searchFields: ['name', 'shortName', 'conductingBody'],
        defaultSort: { displayOrder: 1 },
        softDelete: true,
        revalidateTags: ['exams'],
        publicPath: (doc) => `/exams/${doc.slug as string}`,
        permissions: {
            read: 'exam.read',
            create: 'exam.manage',
            update: 'exam.manage',
            delete: 'exam.manage',
        },
        columns: [
            { name: 'shortName', label: 'Exam' },
            { name: 'category', label: 'Category', type: 'badge' },
            { name: 'level', label: 'Level', type: 'badge' },
            { name: 'examYear', label: 'Year', type: 'number' },
            { name: 'examDateFrom', label: 'Exam date', type: 'date' },
            { name: 'status', label: 'Status', type: 'badge' },
        ],
        fields: [
            { name: 'name', label: 'Full name', type: 'text', required: true, group: 'Basics', colSpan: 2 },
            { name: 'shortName', label: 'Short name', type: 'text', required: true, group: 'Basics' },
            { name: 'slug', label: 'Slug', type: 'slug', required: true, group: 'Basics' },
            { name: 'conductingBody', label: 'Conducting body', type: 'text', required: true, group: 'Basics', colSpan: 2 },
            { name: 'level', label: 'Level', type: 'select', options: EXAM_LEVELS, required: true, group: 'Basics' },
            { name: 'category', label: 'Category', type: 'select', options: EXAM_CATEGORIES, required: true, group: 'Basics' },
            { name: 'mode', label: 'Mode', type: 'multiselect', options: EXAM_MODES, group: 'Basics' },
            { name: 'examYear', label: 'Exam year', type: 'number', required: true, min: 2000, max: 2100, group: 'Basics' },
            { name: 'officialWebsite', label: 'Official website', type: 'text', group: 'Basics', colSpan: 2 },
            { name: 'applicationFee.general', label: 'Fee — General (₹)', type: 'number', group: 'Fees' },
            { name: 'applicationFee.reserved', label: 'Fee — Reserved (₹)', type: 'number', group: 'Fees' },
            { name: 'registrationStart', label: 'Registration starts', type: 'date', group: 'Dates' },
            { name: 'registrationEnd', label: 'Registration ends', type: 'date', group: 'Dates' },
            { name: 'examDateFrom', label: 'Exam date (from)', type: 'date', group: 'Dates' },
            { name: 'examDateTo', label: 'Exam date (to)', type: 'date', group: 'Dates' },
            { name: 'admitCardDate', label: 'Admit card date', type: 'date', group: 'Dates' },
            { name: 'resultDate', label: 'Result date', type: 'date', group: 'Dates' },
            { name: 'counsellingStart', label: 'Counselling starts', type: 'date', group: 'Dates' },
            { name: 'overviewHtml', label: 'Overview', type: 'richtext', group: 'Content', colSpan: 2 },
            { name: 'eligibilityHtml', label: 'Eligibility', type: 'richtext', group: 'Content', colSpan: 2 },
            { name: 'applicationProcessHtml', label: 'Application process', type: 'richtext', group: 'Content', colSpan: 2 },
            { name: 'patternHtml', label: 'Exam pattern', type: 'richtext', group: 'Content', colSpan: 2 },
            { name: 'syllabusHtml', label: 'Syllabus', type: 'richtext', group: 'Content', colSpan: 2 },
            { name: 'preparationTipsHtml', label: 'Preparation tips', type: 'richtext', group: 'Content', colSpan: 2 },
            { name: 'cutoffHtml', label: 'Cut-off notes', type: 'richtext', group: 'Content', colSpan: 2 },
            { name: 'counsellingHtml', label: 'Counselling', type: 'richtext', group: 'Content', colSpan: 2 },
            { name: 'predictorEnabled', label: 'Predictor enabled', type: 'boolean', group: 'Publishing' },
            { name: 'isFeatured', label: 'Featured', type: 'boolean', group: 'Publishing' },
            { name: 'displayOrder', label: 'Display order', type: 'number', group: 'Publishing' },
            statusField,
            ...seoFields,
        ],
    },

    'exam-dates': {
        key: 'exam-dates',
        model: 'ExamDate',
        label: 'Exam dates',
        labelSingular: 'Exam date',
        icon: 'CalendarDays',
        description: 'Event-level schedule rows shown on the exam dates tab.',
        titleField: 'event',
        searchFields: ['event', 'examShortName'],
        defaultSort: { startDate: 1 },
        revalidateTags: ['exams'],
        permissions: {
            read: 'exam.read',
            create: 'exam.manage',
            update: 'exam.manage',
            delete: 'exam.manage',
        },
        columns: [
            { name: 'examShortName', label: 'Exam' },
            { name: 'event', label: 'Event' },
            { name: 'startDate', label: 'Date', type: 'date' },
            { name: 'isKeyDate', label: 'Key date', type: 'boolean' },
            { name: 'isTentative', label: 'Tentative', type: 'boolean' },
        ],
        fields: [
            { name: 'exam', label: 'Exam', type: 'reference', refModel: 'Exam', refLabelField: 'shortName', required: true, group: 'Basics' },
            { name: 'examYear', label: 'Exam year', type: 'number', required: true, group: 'Basics' },
            { name: 'event', label: 'Event', type: 'text', required: true, group: 'Basics', colSpan: 2 },
            { name: 'description', label: 'Description', type: 'textarea', group: 'Basics', colSpan: 2 },
            { name: 'startDate', label: 'Start date', type: 'date', group: 'Dates' },
            { name: 'endDate', label: 'End date', type: 'date', group: 'Dates' },
            { name: 'isKeyDate', label: 'Key date', type: 'boolean', group: 'Display' },
            { name: 'isTentative', label: 'Tentative', type: 'boolean', group: 'Display' },
            { name: 'displayOrder', label: 'Display order', type: 'number', group: 'Display' },
            entityStatusField,
        ],
    },

    predictors: {
        key: 'predictors',
        model: 'Predictor',
        label: 'Predictors',
        labelSingular: 'Predictor',
        icon: 'Target',
        description: 'Predictor configuration: metric, band rules, disclaimer and placement.',
        titleField: 'name',
        slugField: 'slug',
        searchFields: ['name', 'examShortName'],
        defaultSort: { displayOrder: 1 },
        softDelete: true,
        revalidateTags: ['predictors', 'homepage'],
        publicPath: (doc) => `/predictors/${doc.slug as string}`,
        permissions: {
            read: 'predictor.read',
            create: 'predictor.manage',
            update: 'predictor.manage',
            delete: 'predictor.manage',
        },
        columns: [
            { name: 'name', label: 'Predictor' },
            { name: 'examShortName', label: 'Exam' },
            { name: 'metric', label: 'Metric', type: 'badge' },
            { name: 'usageCount', label: 'Runs', type: 'number' },
            { name: 'showOnHomepage', label: 'Homepage', type: 'boolean' },
            { name: 'status', label: 'Status', type: 'badge' },
        ],
        fields: [
            { name: 'name', label: 'Name', type: 'text', required: true, group: 'Basics', colSpan: 2 },
            { name: 'slug', label: 'Slug', type: 'slug', required: true, group: 'Basics' },
            { name: 'exam', label: 'Exam', type: 'reference', refModel: 'Exam', refLabelField: 'shortName', group: 'Basics' },
            { name: 'examShortName', label: 'Exam short name', type: 'text', group: 'Basics' },
            { name: 'subtitle', label: 'Subtitle', type: 'text', group: 'Basics' },
            { name: 'description', label: 'Description', type: 'textarea', group: 'Basics', colSpan: 2 },
            { name: 'icon', label: 'Icon', type: 'text', group: 'Appearance' },
            { name: 'themeColor', label: 'Theme colour', type: 'select', options: THEME_COLORS, group: 'Appearance' },
            { name: 'ctaLabel', label: 'CTA label', type: 'text', group: 'Appearance' },
            { name: 'metric', label: 'Metric', type: 'select', options: ['rank', 'percentile', 'score'], required: true, group: 'Rules' },
            {
                name: 'metricDirection',
                label: 'Metric direction',
                type: 'select',
                options: ['lower_is_better', 'higher_is_better'],
                required: true,
                group: 'Rules',
            },
            { name: 'bandRules', label: 'Band rules (JSON)', type: 'json', group: 'Rules', colSpan: 2, help: 'Array of { band, maxRatio | minRatio }' },
            { name: 'disclaimer', label: 'Disclaimer', type: 'textarea', required: true, group: 'Rules', colSpan: 2 },
            { name: 'showOnHomepage', label: 'Show on homepage', type: 'boolean', group: 'Publishing' },
            { name: 'isFeatured', label: 'Featured', type: 'boolean', group: 'Publishing' },
            { name: 'displayOrder', label: 'Display order', type: 'number', group: 'Publishing' },
            statusField,
            ...seoFields,
        ],
    },

    'loan-providers': {
        key: 'loan-providers',
        model: 'LoanProvider',
        label: 'Loan providers',
        labelSingular: 'Loan provider',
        icon: 'Landmark',
        description: 'Lenders with rates, limits, collateral rules and documents.',
        titleField: 'name',
        slugField: 'slug',
        searchFields: ['name'],
        defaultSort: { displayOrder: 1 },
        softDelete: true,
        revalidateTags: ['loan-providers'],
        publicPath: (doc) => `/education-loans/${doc.slug as string}`,
        permissions: {
            read: 'loan.manage',
            create: 'loan.manage',
            update: 'loan.manage',
            delete: 'loan.manage',
        },
        columns: [
            { name: 'name', label: 'Lender' },
            { name: 'providerType', label: 'Type', type: 'badge' },
            { name: 'interestRateMin', label: 'Rate from', type: 'number' },
            { name: 'maxLoanAmount', label: 'Max amount', type: 'currency' },
            { name: 'status', label: 'Status', type: 'badge' },
        ],
        fields: [
            { name: 'name', label: 'Lender name', type: 'text', required: true, group: 'Basics', colSpan: 2 },
            { name: 'slug', label: 'Slug', type: 'slug', required: true, group: 'Basics' },
            {
                name: 'providerType',
                label: 'Type',
                type: 'select',
                options: ['Public Bank', 'Private Bank', 'NBFC', 'Fintech', 'International'],
                required: true,
                group: 'Basics',
            },
            { name: 'summary', label: 'Summary', type: 'textarea', group: 'Basics', colSpan: 2 },
            { name: 'detailsHtml', label: 'Details', type: 'richtext', group: 'Content', colSpan: 2 },
            { name: 'eligibilityHtml', label: 'Eligibility', type: 'richtext', group: 'Content', colSpan: 2 },
            { name: 'interestRateMin', label: 'Interest rate from (%)', type: 'number', step: 0.05, group: 'Terms' },
            { name: 'interestRateMax', label: 'Interest rate up to (%)', type: 'number', step: 0.05, group: 'Terms' },
            { name: 'maxLoanAmount', label: 'Maximum amount (₹)', type: 'number', group: 'Terms' },
            { name: 'maxLoanAmountWithoutCollateral', label: 'Collateral-free limit (₹)', type: 'number', group: 'Terms' },
            { name: 'collateralRequiredAbove', label: 'Collateral required above (₹)', type: 'number', group: 'Terms' },
            { name: 'processingFeePercent', label: 'Processing fee (%)', type: 'number', step: 0.05, group: 'Terms' },
            { name: 'moratoriumMonths', label: 'Moratorium (months)', type: 'number', group: 'Terms' },
            { name: 'maxTenureYears', label: 'Maximum tenure (years)', type: 'number', group: 'Terms' },
            { name: 'processingTimeDays', label: 'Processing time', type: 'text', group: 'Terms' },
            { name: 'coversAbroad', label: 'Covers study abroad', type: 'boolean', group: 'Terms' },
            { name: 'documentsRequired', label: 'Documents required', type: 'tags', group: 'Terms', colSpan: 2 },
            { name: 'applyUrl', label: 'Apply URL', type: 'text', group: 'Terms', colSpan: 2 },
            { name: 'isFeatured', label: 'Featured', type: 'boolean', group: 'Publishing' },
            { name: 'displayOrder', label: 'Display order', type: 'number', group: 'Publishing' },
            statusField,
            ...seoFields,
        ],
    },

    'loan-products': {
        key: 'loan-products',
        model: 'LoanProduct',
        label: 'Loan products',
        labelSingular: 'Loan product',
        icon: 'Wallet',
        description: 'Individual loan schemes under each lender.',
        titleField: 'name',
        slugField: 'slug',
        searchFields: ['name', 'providerName'],
        defaultSort: { providerName: 1 },
        revalidateTags: ['loan-providers'],
        permissions: {
            read: 'loan.manage',
            create: 'loan.manage',
            update: 'loan.manage',
            delete: 'loan.manage',
        },
        columns: [
            { name: 'name', label: 'Product' },
            { name: 'providerName', label: 'Lender' },
            { name: 'purpose', label: 'Purpose', type: 'badge' },
            { name: 'interestRateMin', label: 'Rate from', type: 'number' },
            { name: 'status', label: 'Status', type: 'badge' },
        ],
        fields: [
            { name: 'provider', label: 'Lender', type: 'reference', refModel: 'LoanProvider', refLabelField: 'name', required: true, group: 'Basics' },
            { name: 'name', label: 'Product name', type: 'text', required: true, group: 'Basics' },
            { name: 'slug', label: 'Slug', type: 'slug', required: true, group: 'Basics' },
            {
                name: 'purpose',
                label: 'Purpose',
                type: 'select',
                options: ['Domestic Study', 'Study Abroad', 'Skill Development', 'Vocational'],
                required: true,
                group: 'Basics',
            },
            { name: 'interestRateMin', label: 'Rate from (%)', type: 'number', step: 0.05, group: 'Terms' },
            { name: 'interestRateMax', label: 'Rate up to (%)', type: 'number', step: 0.05, group: 'Terms' },
            { name: 'minAmount', label: 'Minimum amount (₹)', type: 'number', group: 'Terms' },
            { name: 'maxAmount', label: 'Maximum amount (₹)', type: 'number', group: 'Terms' },
            { name: 'tenureYearsMax', label: 'Maximum tenure (years)', type: 'number', group: 'Terms' },
            { name: 'moratoriumMonths', label: 'Moratorium (months)', type: 'number', group: 'Terms' },
            { name: 'collateralFree', label: 'Collateral free', type: 'boolean', group: 'Terms' },
            { name: 'featuresHtml', label: 'Features', type: 'richtext', group: 'Content', colSpan: 2 },
            { name: 'displayOrder', label: 'Display order', type: 'number', group: 'Publishing' },
            entityStatusField,
        ],
    },

    scholarships: {
        key: 'scholarships',
        model: 'Scholarship',
        label: 'Scholarships',
        labelSingular: 'Scholarship',
        icon: 'Award',
        description: 'Scholarship schemes with eligibility, benefit and deadlines.',
        titleField: 'name',
        slugField: 'slug',
        searchFields: ['name', 'provider'],
        defaultSort: { applicationDeadline: 1 },
        softDelete: true,
        revalidateTags: ['scholarships'],
        publicPath: (doc) => `/scholarships/${doc.slug as string}`,
        permissions: {
            read: 'scholarship.manage',
            create: 'scholarship.manage',
            update: 'scholarship.manage',
            delete: 'scholarship.manage',
        },
        columns: [
            { name: 'name', label: 'Scholarship' },
            { name: 'provider', label: 'Provider' },
            { name: 'benefitType', label: 'Benefit', type: 'badge' },
            { name: 'amountMax', label: 'Up to', type: 'currency' },
            { name: 'applicationDeadline', label: 'Deadline', type: 'date' },
            { name: 'status', label: 'Status', type: 'badge' },
        ],
        fields: [
            { name: 'name', label: 'Name', type: 'text', required: true, group: 'Basics', colSpan: 2 },
            { name: 'slug', label: 'Slug', type: 'slug', required: true, group: 'Basics' },
            { name: 'provider', label: 'Provider', type: 'text', required: true, group: 'Basics' },
            {
                name: 'providerType',
                label: 'Provider type',
                type: 'select',
                options: ['Government', 'Private', 'Institute', 'NGO', 'International'],
                required: true,
                group: 'Basics',
            },
            {
                name: 'benefitType',
                label: 'Benefit type',
                type: 'select',
                options: ['Full Tuition', 'Partial Tuition', 'Fixed Amount', 'Monthly Stipend', 'Other'],
                required: true,
                group: 'Benefit',
            },
            { name: 'amountMin', label: 'Amount from (₹)', type: 'number', group: 'Benefit' },
            { name: 'amountMax', label: 'Amount up to (₹)', type: 'number', group: 'Benefit' },
            { name: 'amountNote', label: 'Amount note', type: 'text', group: 'Benefit', colSpan: 2 },
            { name: 'description', label: 'Description', type: 'textarea', group: 'Content', colSpan: 2 },
            { name: 'detailsHtml', label: 'Details', type: 'richtext', group: 'Content', colSpan: 2 },
            { name: 'eligibilityHtml', label: 'Eligibility', type: 'richtext', group: 'Content', colSpan: 2 },
            { name: 'documentsRequired', label: 'Documents', type: 'tags', group: 'Content', colSpan: 2 },
            { name: 'targetLevels', label: 'Target levels', type: 'multiselect', options: COURSE_LEVELS, group: 'Targeting' },
            { name: 'targetCategories', label: 'Target categories', type: 'tags', group: 'Targeting' },
            { name: 'minPercentage', label: 'Minimum marks (%)', type: 'number', min: 0, max: 100, group: 'Targeting' },
            { name: 'maxFamilyIncome', label: 'Maximum family income (₹)', type: 'number', group: 'Targeting' },
            { name: 'applicationStart', label: 'Application starts', type: 'date', group: 'Dates' },
            { name: 'applicationDeadline', label: 'Deadline', type: 'date', group: 'Dates' },
            { name: 'applicationUrl', label: 'Application URL', type: 'text', group: 'Dates', colSpan: 2 },
            { name: 'isFeatured', label: 'Featured', type: 'boolean', group: 'Publishing' },
            statusField,
            ...seoFields,
        ],
    },

    counsellors: {
        key: 'counsellors',
        model: 'Counsellor',
        label: 'Counsellors',
        labelSingular: 'Counsellor',
        icon: 'UserCheck',
        description: 'Counselling team, specialisations, availability and load.',
        titleField: 'name',
        slugField: 'slug',
        searchFields: ['name', 'email', 'designation'],
        defaultSort: { displayOrder: 1 },
        softDelete: true,
        revalidateTags: ['counsellors'],
        publicPath: (doc) => `/counsellors/${doc.slug as string}`,
        permissions: {
            read: 'counselling.read',
            create: 'counsellor.manage',
            update: 'counsellor.manage',
            delete: 'counsellor.manage',
        },
        columns: [
            { name: 'name', label: 'Counsellor' },
            { name: 'designation', label: 'Designation' },
            { name: 'experienceYears', label: 'Experience', type: 'number' },
            { name: 'activeLeadCount', label: 'Active leads', type: 'number' },
            { name: 'isAcceptingLeads', label: 'Accepting', type: 'boolean' },
            { name: 'status', label: 'Status', type: 'badge' },
        ],
        fields: [
            { name: 'name', label: 'Name', type: 'text', required: true, group: 'Basics' },
            { name: 'slug', label: 'Slug', type: 'slug', required: true, group: 'Basics' },
            { name: 'designation', label: 'Designation', type: 'text', group: 'Basics' },
            { name: 'email', label: 'Email', type: 'text', required: true, group: 'Basics' },
            { name: 'phone', label: 'Phone', type: 'text', group: 'Basics' },
            { name: 'bio', label: 'Bio', type: 'textarea', group: 'Basics', colSpan: 2 },
            { name: 'languages', label: 'Languages', type: 'tags', group: 'Expertise' },
            { name: 'specializations', label: 'Specialisations', type: 'tags', group: 'Expertise' },
            { name: 'qualifications', label: 'Qualifications', type: 'tags', group: 'Expertise' },
            { name: 'experienceYears', label: 'Experience (years)', type: 'number', group: 'Expertise' },
            { name: 'freeSessionMinutes', label: 'Free session (minutes)', type: 'number', group: 'Sessions' },
            { name: 'paidSessionMinutes', label: 'Paid session (minutes)', type: 'number', group: 'Sessions' },
            { name: 'paidSessionFee', label: 'Paid session fee (₹)', type: 'number', group: 'Sessions' },
            { name: 'maxDailyBookings', label: 'Max bookings per day', type: 'number', group: 'Sessions' },
            { name: 'meetingLinkTemplate', label: 'Meeting link', type: 'text', group: 'Sessions', colSpan: 2 },
            { name: 'availability', label: 'Availability (JSON)', type: 'json', group: 'Sessions', colSpan: 2, help: 'Array of { weekday, startTime, endTime, isActive }' },
            { name: 'isAcceptingLeads', label: 'Accepting new leads', type: 'boolean', group: 'Publishing' },
            { name: 'isFeatured', label: 'Featured', type: 'boolean', group: 'Publishing' },
            { name: 'displayOrder', label: 'Display order', type: 'number', group: 'Publishing' },
            entityStatusField,
        ],
    },

    articles: {
        key: 'articles',
        model: 'Article',
        label: 'Articles',
        labelSingular: 'Article',
        icon: 'Newspaper',
        description: 'Editorial articles with SEO, FAQ schema and publishing workflow.',
        titleField: 'title',
        slugField: 'slug',
        searchFields: ['title', 'excerpt', 'category'],
        defaultSort: { updatedAt: -1 },
        softDelete: true,
        revalidateTags: ['articles'],
        publicPath: (doc) => `/articles/${doc.slug as string}`,
        permissions: {
            read: 'article.read',
            create: 'article.create',
            update: 'article.update',
            delete: 'article.delete',
        },
        columns: [
            { name: 'title', label: 'Title' },
            { name: 'category', label: 'Category', type: 'badge' },
            { name: 'authorName', label: 'Author' },
            { name: 'viewCount', label: 'Views', type: 'number' },
            { name: 'status', label: 'Status', type: 'badge' },
            { name: 'publishedAt', label: 'Published', type: 'date' },
        ],
        fields: [
            { name: 'title', label: 'Title', type: 'text', required: true, group: 'Basics', colSpan: 2 },
            { name: 'slug', label: 'Slug', type: 'slug', required: true, group: 'Basics' },
            { name: 'category', label: 'Category', type: 'text', required: true, group: 'Basics' },
            { name: 'tags', label: 'Tags', type: 'tags', group: 'Basics', colSpan: 2 },
            { name: 'excerpt', label: 'Excerpt', type: 'textarea', group: 'Basics', colSpan: 2 },
            { name: 'contentHtml', label: 'Content', type: 'richtext', required: true, group: 'Content', colSpan: 2 },
            { name: 'authorName', label: 'Author name', type: 'text', group: 'Attribution' },
            { name: 'readingTimeMinutes', label: 'Reading time (min)', type: 'number', group: 'Attribution' },
            { name: 'featuredImage.url', label: 'Featured image URL', type: 'text', group: 'Media', colSpan: 2 },
            { name: 'featuredImage.alt', label: 'Featured image alt text', type: 'text', group: 'Media', colSpan: 2 },
            { name: 'isFeatured', label: 'Featured', type: 'boolean', group: 'Publishing' },
            { name: 'isTrending', label: 'Trending', type: 'boolean', group: 'Publishing' },
            { name: 'publishedAt', label: 'Publish date', type: 'datetime', group: 'Publishing' },
            { name: 'scheduledFor', label: 'Scheduled for', type: 'datetime', group: 'Publishing' },
            statusField,
            ...seoFields,
        ],
    },

    news: {
        key: 'news',
        model: 'NewsPost',
        label: 'News & updates',
        labelSingular: 'Update',
        icon: 'Megaphone',
        description: 'Trending feed items: counselling, exam dates, results and deadlines.',
        titleField: 'title',
        slugField: 'slug',
        searchFields: ['title', 'summary'],
        defaultSort: { publishDate: -1 },
        softDelete: true,
        revalidateTags: ['news', 'trending', 'homepage'],
        publicPath: (doc) => `/news/${doc.slug as string}`,
        permissions: {
            read: 'article.read',
            create: 'news.manage',
            update: 'news.manage',
            delete: 'news.manage',
        },
        columns: [
            { name: 'title', label: 'Update' },
            { name: 'category', label: 'Category', type: 'badge' },
            { name: 'badge', label: 'Badge', type: 'badge' },
            { name: 'priority', label: 'Priority', type: 'number' },
            { name: 'publishDate', label: 'Published', type: 'date' },
            { name: 'status', label: 'Status', type: 'badge' },
        ],
        fields: [
            { name: 'title', label: 'Title', type: 'text', required: true, group: 'Basics', colSpan: 2 },
            { name: 'slug', label: 'Slug', type: 'slug', required: true, group: 'Basics' },
            { name: 'category', label: 'Category', type: 'select', options: TRENDING_CATEGORIES, required: true, group: 'Basics' },
            {
                name: 'badge',
                label: 'Badge',
                type: 'select',
                options: ['New', 'Hot', 'Live', 'Update', 'Closing Soon'],
                group: 'Basics',
            },
            { name: 'priority', label: 'Priority', type: 'number', group: 'Basics', help: 'Higher shows first' },
            { name: 'summary', label: 'Summary', type: 'textarea', group: 'Content', colSpan: 2 },
            { name: 'contentHtml', label: 'Content', type: 'richtext', group: 'Content', colSpan: 2 },
            { name: 'targetExam', label: 'Target exam', type: 'reference', refModel: 'Exam', refLabelField: 'shortName', group: 'Targeting' },
            { name: 'targetState', label: 'Target state', type: 'reference', refModel: 'State', refLabelField: 'name', group: 'Targeting' },
            { name: 'internalUrl', label: 'Internal URL', type: 'text', group: 'Links', colSpan: 2 },
            { name: 'externalUrl', label: 'External URL', type: 'text', group: 'Links', colSpan: 2 },
            { name: 'publishDate', label: 'Publish date', type: 'datetime', required: true, group: 'Publishing' },
            { name: 'expiryDate', label: 'Expiry date', type: 'datetime', group: 'Publishing' },
            { name: 'showInTrending', label: 'Show in trending feed', type: 'boolean', group: 'Publishing' },
            { name: 'isFeatured', label: 'Featured', type: 'boolean', group: 'Publishing' },
            statusField,
            ...seoFields,
        ],
    },

    resources: {
        key: 'resources',
        model: 'Resource',
        label: 'Resources',
        labelSingular: 'Resource',
        icon: 'FileStack',
        description: 'Papers, mock tests, guides, e-books, webinars and calendars.',
        titleField: 'title',
        slugField: 'slug',
        searchFields: ['title', 'description'],
        defaultSort: { updatedAt: -1 },
        softDelete: true,
        revalidateTags: ['resources'],
        permissions: {
            read: 'article.read',
            create: 'resource.manage',
            update: 'resource.manage',
            delete: 'resource.manage',
        },
        columns: [
            { name: 'title', label: 'Resource' },
            { name: 'type', label: 'Type', type: 'badge' },
            { name: 'relatedExamName', label: 'Exam' },
            { name: 'year', label: 'Year', type: 'number' },
            { name: 'downloadCount', label: 'Downloads', type: 'number' },
            { name: 'status', label: 'Status', type: 'badge' },
        ],
        fields: [
            { name: 'title', label: 'Title', type: 'text', required: true, group: 'Basics', colSpan: 2 },
            { name: 'slug', label: 'Slug', type: 'slug', required: true, group: 'Basics' },
            { name: 'type', label: 'Type', type: 'select', options: RESOURCE_TYPES, required: true, group: 'Basics' },
            { name: 'relatedExam', label: 'Related exam', type: 'reference', refModel: 'Exam', refLabelField: 'shortName', group: 'Basics' },
            { name: 'year', label: 'Year', type: 'number', group: 'Basics' },
            { name: 'subject', label: 'Subject', type: 'text', group: 'Basics' },
            { name: 'description', label: 'Description', type: 'textarea', group: 'Content', colSpan: 2 },
            { name: 'contentHtml', label: 'Content', type: 'richtext', group: 'Content', colSpan: 2 },
            { name: 'fileUrl', label: 'File URL', type: 'text', group: 'Files', colSpan: 2 },
            { name: 'fileSizeKb', label: 'File size (KB)', type: 'number', group: 'Files' },
            { name: 'externalUrl', label: 'External URL', type: 'text', group: 'Files' },
            { name: 'videoUrl', label: 'Video URL', type: 'text', group: 'Files', colSpan: 2 },
            { name: 'durationMinutes', label: 'Duration (minutes)', type: 'number', group: 'Test settings' },
            { name: 'questionCount', label: 'Questions', type: 'number', group: 'Test settings' },
            { name: 'difficulty', label: 'Difficulty', type: 'select', options: ['Easy', 'Moderate', 'Hard'], group: 'Test settings' },
            { name: 'webinarAt', label: 'Webinar date & time', type: 'datetime', group: 'Test settings' },
            { name: 'speakerName', label: 'Speaker', type: 'text', group: 'Test settings' },
            { name: 'isFree', label: 'Free', type: 'boolean', group: 'Access' },
            { name: 'price', label: 'Price (₹)', type: 'number', group: 'Access' },
            { name: 'requiresLogin', label: 'Requires login', type: 'boolean', group: 'Access' },
            { name: 'isFeatured', label: 'Featured', type: 'boolean', group: 'Publishing' },
            statusField,
            ...seoFields,
        ],
    },

    faqs: {
        key: 'faqs',
        model: 'FAQ',
        label: 'FAQs',
        labelSingular: 'FAQ',
        icon: 'CircleHelp',
        description: 'Reusable FAQ entries scoped globally or to an entity.',
        titleField: 'question',
        searchFields: ['question', 'category'],
        defaultSort: { displayOrder: 1 },
        revalidateTags: ['homepage'],
        permissions: {
            read: 'article.read',
            create: 'resource.manage',
            update: 'resource.manage',
            delete: 'resource.manage',
        },
        columns: [
            { name: 'question', label: 'Question' },
            { name: 'category', label: 'Category', type: 'badge' },
            { name: 'scope', label: 'Scope', type: 'badge' },
            { name: 'displayOrder', label: 'Order', type: 'number' },
            { name: 'status', label: 'Status', type: 'badge' },
        ],
        fields: [
            { name: 'question', label: 'Question', type: 'text', required: true, group: 'Basics', colSpan: 2 },
            { name: 'answerHtml', label: 'Answer', type: 'richtext', required: true, group: 'Basics', colSpan: 2 },
            { name: 'category', label: 'Category', type: 'text', required: true, group: 'Basics' },
            {
                name: 'scope',
                label: 'Scope',
                type: 'select',
                options: ['global', 'college', 'course', 'exam', 'loan', 'counselling', 'predictor'],
                required: true,
                group: 'Basics',
            },
            { name: 'isFeatured', label: 'Featured', type: 'boolean', group: 'Publishing' },
            { name: 'displayOrder', label: 'Display order', type: 'number', group: 'Publishing' },
            entityStatusField,
        ],
    },

    states: {
        key: 'states',
        model: 'State',
        label: 'States',
        labelSingular: 'State',
        icon: 'Map',
        description: 'States and union territories used by filters and landing pages.',
        titleField: 'name',
        slugField: 'slug',
        searchFields: ['name', 'code'],
        defaultSort: { displayOrder: 1 },
        revalidateTags: ['geo'],
        publicPath: (doc) => `/colleges/state/${doc.slug as string}`,
        permissions: {
            read: 'college.read',
            create: 'settings.manage',
            update: 'settings.manage',
            delete: 'settings.manage',
        },
        columns: [
            { name: 'name', label: 'State' },
            { name: 'code', label: 'Code' },
            { name: 'region', label: 'Region', type: 'badge' },
            { name: 'collegeCount', label: 'Colleges', type: 'number' },
            { name: 'isFeatured', label: 'Featured', type: 'boolean' },
        ],
        fields: [
            { name: 'name', label: 'Name', type: 'text', required: true, group: 'Basics' },
            { name: 'slug', label: 'Slug', type: 'slug', required: true, group: 'Basics' },
            { name: 'code', label: 'Code', type: 'text', required: true, group: 'Basics' },
            {
                name: 'region',
                label: 'Region',
                type: 'select',
                options: ['North', 'South', 'East', 'West', 'Central', 'North-East'],
                group: 'Basics',
            },
            { name: 'isUnionTerritory', label: 'Union territory', type: 'boolean', group: 'Basics' },
            { name: 'counsellingAuthority', label: 'Counselling authority', type: 'text', group: 'Counselling', colSpan: 2 },
            { name: 'counsellingWebsite', label: 'Counselling website', type: 'text', group: 'Counselling', colSpan: 2 },
            { name: 'description', label: 'Description', type: 'textarea', group: 'Content', colSpan: 2 },
            { name: 'isFeatured', label: 'Featured', type: 'boolean', group: 'Publishing' },
            { name: 'displayOrder', label: 'Display order', type: 'number', group: 'Publishing' },
            entityStatusField,
            ...seoFields,
        ],
    },

    cities: {
        key: 'cities',
        model: 'City',
        label: 'Cities',
        labelSingular: 'City',
        icon: 'MapPin',
        description: 'Cities used by filters and city landing pages.',
        titleField: 'name',
        slugField: 'slug',
        searchFields: ['name', 'stateName'],
        defaultSort: { stateName: 1, name: 1 },
        revalidateTags: ['geo'],
        publicPath: (doc) => `/colleges/city/${doc.slug as string}`,
        permissions: {
            read: 'college.read',
            create: 'settings.manage',
            update: 'settings.manage',
            delete: 'settings.manage',
        },
        columns: [
            { name: 'name', label: 'City' },
            { name: 'stateName', label: 'State' },
            { name: 'collegeCount', label: 'Colleges', type: 'number' },
            { name: 'isFeatured', label: 'Featured', type: 'boolean' },
        ],
        fields: [
            { name: 'name', label: 'Name', type: 'text', required: true, group: 'Basics' },
            { name: 'slug', label: 'Slug', type: 'slug', required: true, group: 'Basics' },
            { name: 'state', label: 'State', type: 'reference', refModel: 'State', refLabelField: 'name', required: true, group: 'Basics' },
            { name: 'tier', label: 'Tier', type: 'select', options: ['1', '2', '3'], group: 'Basics' },
            { name: 'isMetro', label: 'Metro city', type: 'boolean', group: 'Basics' },
            { name: 'description', label: 'Description', type: 'textarea', group: 'Content', colSpan: 2 },
            { name: 'isFeatured', label: 'Featured', type: 'boolean', group: 'Publishing' },
            { name: 'displayOrder', label: 'Display order', type: 'number', group: 'Publishing' },
            entityStatusField,
            ...seoFields,
        ],
    },

    rankings: {
        key: 'rankings',
        model: 'Ranking',
        label: 'Rankings',
        labelSingular: 'Ranking',
        icon: 'Trophy',
        description: 'Publisher-wise ranking rows attached to colleges.',
        titleField: 'collegeName',
        searchFields: ['collegeName', 'publisher', 'categoryName'],
        defaultSort: { year: -1, rank: 1 },
        revalidateTags: ['colleges'],
        permissions: {
            read: 'college.read',
            create: 'ranking.manage',
            update: 'ranking.manage',
            delete: 'ranking.manage',
        },
        columns: [
            { name: 'collegeName', label: 'College' },
            { name: 'publisher', label: 'Publisher' },
            { name: 'categoryName', label: 'Category' },
            { name: 'year', label: 'Year', type: 'number' },
            { name: 'rank', label: 'Rank', type: 'number' },
        ],
        fields: [
            { name: 'college', label: 'College', type: 'reference', refModel: 'College', refLabelField: 'name', required: true, group: 'Basics' },
            { name: 'publisher', label: 'Publisher', type: 'text', required: true, group: 'Basics' },
            { name: 'categoryName', label: 'Category', type: 'text', required: true, group: 'Basics' },
            { name: 'year', label: 'Year', type: 'number', required: true, group: 'Basics' },
            { name: 'rank', label: 'Rank', type: 'number', required: true, group: 'Basics' },
            { name: 'score', label: 'Score', type: 'number', step: 0.01, group: 'Basics' },
            { name: 'sourceUrl', label: 'Source URL', type: 'text', group: 'Basics', colSpan: 2 },
            entityStatusField,
        ],
    },

    users: {
        key: 'users',
        model: 'User',
        label: 'Users',
        labelSingular: 'User',
        icon: 'Users',
        description: 'Accounts, roles and status. Passwords are never shown or logged.',
        titleField: 'name',
        searchFields: ['name', 'email', 'phone'],
        defaultSort: { createdAt: -1 },
        softDelete: true,
        permissions: {
            read: 'users.read',
            create: 'users.manage',
            update: 'users.manage',
            delete: 'users.manage',
        },
        columns: [
            { name: 'name', label: 'Name' },
            { name: 'email', label: 'Email' },
            { name: 'roles', label: 'Roles', type: 'badge' },
            { name: 'status', label: 'Status', type: 'badge' },
            { name: 'lastLoginAt', label: 'Last login', type: 'date' },
            { name: 'createdAt', label: 'Joined', type: 'date' },
        ],
        fields: [
            { name: 'name', label: 'Name', type: 'text', required: true, group: 'Basics' },
            { name: 'email', label: 'Email', type: 'text', required: true, group: 'Basics' },
            { name: 'phone', label: 'Phone', type: 'text', group: 'Basics' },
            { name: 'roles', label: 'Roles', type: 'multiselect', options: ROLES, required: true, group: 'Access' },
            {
                name: 'status',
                label: 'Status',
                type: 'select',
                options: ['active', 'suspended', 'pending'],
                required: true,
                group: 'Access',
            },
            { name: 'extraPermissions', label: 'Extra permissions', type: 'tags', group: 'Access', colSpan: 2 },
            { name: 'deniedPermissions', label: 'Denied permissions', type: 'tags', group: 'Access', colSpan: 2 },
        ],
    },

    redirects: {
        key: 'redirects',
        model: 'Redirect',
        label: 'Redirects',
        labelSingular: 'Redirect',
        icon: 'Share2',
        description: 'Source → destination redirects with hit counters.',
        titleField: 'source',
        searchFields: ['source', 'destination'],
        defaultSort: { updatedAt: -1 },
        permissions: {
            read: 'redirect.manage',
            create: 'redirect.manage',
            update: 'redirect.manage',
            delete: 'redirect.manage',
        },
        columns: [
            { name: 'source', label: 'Source' },
            { name: 'destination', label: 'Destination' },
            { name: 'statusCode', label: 'Code', type: 'number' },
            { name: 'hitCount', label: 'Hits', type: 'number' },
            { name: 'status', label: 'Status', type: 'badge' },
        ],
        fields: [
            { name: 'source', label: 'Source path', type: 'text', required: true, group: 'Basics', colSpan: 2 },
            { name: 'destination', label: 'Destination path', type: 'text', required: true, group: 'Basics', colSpan: 2 },
            { name: 'statusCode', label: 'Status code', type: 'select', options: ['301', '302', '307', '308'], group: 'Basics' },
            { name: 'isRegex', label: 'Treat source as regex', type: 'boolean', group: 'Basics' },
            { name: 'note', label: 'Note', type: 'text', group: 'Basics', colSpan: 2 },
            entityStatusField,
        ],
    },

    'email-templates': {
        key: 'email-templates',
        model: 'EmailTemplate',
        label: 'Email templates',
        labelSingular: 'Email template',
        icon: 'Mail',
        description: 'Transactional email copy with {{variable}} placeholders.',
        titleField: 'name',
        searchFields: ['name', 'key', 'subject'],
        defaultSort: { name: 1 },
        permissions: {
            read: 'template.manage',
            create: 'template.manage',
            update: 'template.manage',
            delete: 'template.manage',
        },
        columns: [
            { name: 'name', label: 'Template' },
            { name: 'key', label: 'Key' },
            { name: 'subject', label: 'Subject' },
            { name: 'status', label: 'Status', type: 'badge' },
        ],
        fields: [
            { name: 'key', label: 'Key', type: 'text', required: true, group: 'Basics' },
            { name: 'name', label: 'Name', type: 'text', required: true, group: 'Basics' },
            { name: 'subject', label: 'Subject', type: 'text', required: true, group: 'Basics', colSpan: 2 },
            {
                name: 'bodyHtml',
                label: 'Email body',
                type: 'richtext',
                required: true,
                group: 'Content',
                colSpan: 2,
                htmlPolicy: 'email',
                help: 'Use {{variable}} placeholders. Inline styles are preserved because email clients ignore stylesheets.',
            },
            { name: 'bodyText', label: 'Plain-text body', type: 'textarea', group: 'Content', colSpan: 2 },
            { name: 'availableVariables', label: 'Available variables', type: 'tags', group: 'Content', colSpan: 2 },
            { name: 'ccEmails', label: 'CC', type: 'tags', group: 'Delivery' },
            { name: 'bccEmails', label: 'BCC', type: 'tags', group: 'Delivery' },
            entityStatusField,
        ],
    },

    'whatsapp-templates': {
        key: 'whatsapp-templates',
        model: 'WhatsAppTemplate',
        label: 'WhatsApp templates',
        labelSingular: 'WhatsApp template',
        icon: 'MessageCircle',
        description: 'WhatsApp message copy and provider approval state.',
        titleField: 'name',
        searchFields: ['name', 'key'],
        defaultSort: { name: 1 },
        permissions: {
            read: 'template.manage',
            create: 'template.manage',
            update: 'template.manage',
            delete: 'template.manage',
        },
        columns: [
            { name: 'name', label: 'Template' },
            { name: 'key', label: 'Key' },
            { name: 'approvalStatus', label: 'Approval', type: 'badge' },
            { name: 'status', label: 'Status', type: 'badge' },
        ],
        fields: [
            { name: 'key', label: 'Key', type: 'text', required: true, group: 'Basics' },
            { name: 'name', label: 'Name', type: 'text', required: true, group: 'Basics' },
            { name: 'providerTemplateName', label: 'Provider template name', type: 'text', group: 'Basics' },
            { name: 'language', label: 'Language', type: 'text', group: 'Basics' },
            { name: 'bodyText', label: 'Message body', type: 'textarea', required: true, group: 'Content', colSpan: 2 },
            { name: 'availableVariables', label: 'Available variables', type: 'tags', group: 'Content', colSpan: 2 },
            {
                name: 'approvalStatus',
                label: 'Approval status',
                type: 'select',
                options: ['draft', 'submitted', 'approved', 'rejected'],
                group: 'Publishing',
            },
            entityStatusField,
        ],
    },

    forms: {
        key: 'forms',
        model: 'FormDefinition',
        label: 'Forms',
        labelSingular: 'Form',
        icon: 'ClipboardList',
        description: 'Configurable lead capture forms.',
        titleField: 'name',
        slugField: 'slug',
        searchFields: ['name', 'key'],
        defaultSort: { name: 1 },
        permissions: {
            read: 'form.manage',
            create: 'form.manage',
            update: 'form.manage',
            delete: 'form.manage',
        },
        columns: [
            { name: 'name', label: 'Form' },
            { name: 'key', label: 'Key' },
            { name: 'leadSource', label: 'Lead source', type: 'badge' },
            { name: 'submissionCount', label: 'Submissions', type: 'number' },
            { name: 'status', label: 'Status', type: 'badge' },
        ],
        fields: [
            { name: 'key', label: 'Key', type: 'text', required: true, group: 'Basics' },
            { name: 'name', label: 'Name', type: 'text', required: true, group: 'Basics' },
            { name: 'slug', label: 'Slug', type: 'slug', required: true, group: 'Basics' },
            { name: 'description', label: 'Description', type: 'textarea', group: 'Basics', colSpan: 2 },
            { name: 'fields', label: 'Fields (JSON)', type: 'json', group: 'Schema', colSpan: 2 },
            { name: 'submitLabel', label: 'Submit label', type: 'text', group: 'Behaviour' },
            { name: 'successMessage', label: 'Success message', type: 'text', group: 'Behaviour', colSpan: 2 },
            { name: 'leadSource', label: 'Lead source', type: 'select', options: LEAD_SOURCES, group: 'Behaviour' },
            { name: 'notifyEmails', label: 'Notify emails', type: 'tags', group: 'Behaviour', colSpan: 2 },
            entityStatusField,
        ],
    },

    pages: {
        key: 'pages',
        model: 'StaticPage',
        label: 'Pages',
        labelSingular: 'Page',
        icon: 'FileText',
        description: 'Standalone company, support and legal pages rendered at /{slug}.',
        titleField: 'title',
        slugField: 'slug',
        searchFields: ['title', 'slug', 'excerpt'],
        defaultSort: { group: 1, displayOrder: 1 },
        softDelete: true,
        revalidateTags: ['pages'],
        publicPath: (doc) => `/${doc.slug as string}`,
        permissions: {
            read: 'page.manage',
            create: 'page.manage',
            update: 'page.manage',
            delete: 'page.manage',
        },
        columns: [
            { name: 'title', label: 'Page' },
            { name: 'slug', label: 'URL' },
            { name: 'group', label: 'Group', type: 'badge' },
            { name: 'status', label: 'Status', type: 'badge' },
            { name: 'updatedAt', label: 'Updated', type: 'date' },
        ],
        fields: [
            { name: 'title', label: 'Page title', type: 'text', required: true, group: 'Basics', colSpan: 2 },
            {
                name: 'slug',
                label: 'Slug',
                type: 'slug',
                required: true,
                group: 'Basics',
                help: 'The page is served at /slug. Application routes such as "colleges" or "admin" are reserved.',
            },
            {
                name: 'group',
                label: 'Group',
                type: 'select',
                options: ['company', 'legal', 'support', 'other'],
                required: true,
                group: 'Basics',
            },
            { name: 'heroEyebrow', label: 'Eyebrow text', type: 'text', group: 'Basics' },
            { name: 'displayOrder', label: 'Display order', type: 'number', group: 'Basics' },
            { name: 'excerpt', label: 'Short summary', type: 'textarea', group: 'Basics', colSpan: 2 },
            { name: 'contentHtml', label: 'Page content', type: 'richtext', required: true, group: 'Content', colSpan: 2 },
            {
                name: 'showLastUpdated',
                label: 'Show "last updated" date',
                type: 'boolean',
                group: 'Publishing',
                help: 'Recommended for legal and policy pages.',
            },
            { name: 'publishedAt', label: 'Publish date', type: 'datetime', group: 'Publishing' },
            statusField,
            ...seoFields,
        ],
    },

    'contact-submissions': {
        key: 'contact-submissions',
        model: 'ContactSubmission',
        label: 'Contact submissions',
        labelSingular: 'Contact submission',
        icon: 'Mail',
        description: 'Messages received through the contact form.',
        titleField: 'subject',
        searchFields: ['name', 'email', 'subject'],
        defaultSort: { createdAt: -1 },
        permissions: {
            read: 'lead.read',
            create: 'lead.create',
            update: 'lead.update',
            delete: 'lead.delete',
        },
        columns: [
            { name: 'name', label: 'From' },
            { name: 'email', label: 'Email' },
            { name: 'subject', label: 'Subject' },
            { name: 'handled', label: 'Handled', type: 'boolean' },
            { name: 'createdAt', label: 'Received', type: 'date' },
        ],
        fields: [
            { name: 'name', label: 'Name', type: 'text', required: true, group: 'Basics' },
            { name: 'email', label: 'Email', type: 'text', required: true, group: 'Basics' },
            { name: 'phone', label: 'Phone', type: 'text', group: 'Basics' },
            { name: 'subject', label: 'Subject', type: 'text', required: true, group: 'Basics' },
            { name: 'message', label: 'Message', type: 'textarea', required: true, group: 'Basics', colSpan: 2 },
            { name: 'handled', label: 'Marked handled', type: 'boolean', group: 'Workflow' },
        ],
    },

    reviews: {
        key: 'reviews',
        model: 'Review',
        label: 'Reviews',
        labelSingular: 'Review',
        icon: 'Star',
        description: 'College reviews awaiting moderation or already published.',
        titleField: 'title',
        searchFields: ['title', 'collegeName', 'authorName'],
        defaultSort: { createdAt: -1 },
        softDelete: true,
        revalidateTags: ['reviews'],
        permissions: {
            read: 'review.moderate',
            create: 'review.moderate',
            update: 'review.moderate',
            delete: 'review.moderate',
        },
        columns: [
            { name: 'collegeName', label: 'College' },
            { name: 'title', label: 'Review' },
            { name: 'authorName', label: 'Author' },
            { name: 'ratings.overall', label: 'Rating', type: 'number' },
            { name: 'moderationStatus', label: 'Moderation', type: 'badge' },
            { name: 'createdAt', label: 'Received', type: 'date' },
        ],
        fields: [
            { name: 'title', label: 'Headline', type: 'text', required: true, group: 'Content', colSpan: 2 },
            { name: 'reviewText', label: 'Review', type: 'textarea', required: true, group: 'Content', colSpan: 2 },
            { name: 'pros', label: 'Pros', type: 'textarea', group: 'Content' },
            { name: 'cons', label: 'Cons', type: 'textarea', group: 'Content' },
            { name: 'authorName', label: 'Author name', type: 'text', group: 'Author' },
            { name: 'isAnonymous', label: 'Anonymous', type: 'boolean', group: 'Author' },
            { name: 'courseName', label: 'Course', type: 'text', group: 'Author' },
            { name: 'passingYear', label: 'Passing year', type: 'number', group: 'Author' },
            { name: 'ratings.overall', label: 'Overall rating', type: 'number', min: 1, max: 5, step: 0.1, group: 'Ratings' },
            { name: 'ratings.placement', label: 'Placement', type: 'number', min: 1, max: 5, step: 0.1, group: 'Ratings' },
            { name: 'ratings.faculty', label: 'Faculty', type: 'number', min: 1, max: 5, step: 0.1, group: 'Ratings' },
            { name: 'ratings.infrastructure', label: 'Infrastructure', type: 'number', min: 1, max: 5, step: 0.1, group: 'Ratings' },
            { name: 'ratings.campusLife', label: 'Campus life', type: 'number', min: 1, max: 5, step: 0.1, group: 'Ratings' },
            { name: 'ratings.valueForMoney', label: 'Value for money', type: 'number', min: 1, max: 5, step: 0.1, group: 'Ratings' },
            {
                name: 'moderationStatus',
                label: 'Moderation status',
                type: 'select',
                options: MODERATION_STATUSES,
                required: true,
                group: 'Moderation',
            },
            { name: 'moderationNote', label: 'Moderation note', type: 'textarea', group: 'Moderation', colSpan: 2 },
            { name: 'isFeatured', label: 'Feature this review', type: 'boolean', group: 'Moderation' },
        ],
    },

    counselling: {
        key: 'counselling',
        model: 'CounsellingBooking',
        label: 'Bookings',
        labelSingular: 'Booking',
        icon: 'CalendarCheck',
        description: 'Counselling sessions with status, counsellor and notes.',
        titleField: 'reference',
        searchFields: ['reference', 'studentName', 'phone', 'email'],
        defaultSort: { createdAt: -1 },
        permissions: {
            read: 'counselling.read',
            create: 'counselling.manage',
            update: 'counselling.manage',
            delete: 'counselling.manage',
        },
        columns: [
            { name: 'reference', label: 'Reference' },
            { name: 'studentName', label: 'Student' },
            { name: 'counsellorName', label: 'Counsellor' },
            { name: 'type', label: 'Type', type: 'badge' },
            { name: 'scheduledAt', label: 'Scheduled', type: 'date' },
            { name: 'status', label: 'Status', type: 'badge' },
        ],
        fields: [
            { name: 'studentName', label: 'Student name', type: 'text', required: true, group: 'Student' },
            { name: 'phone', label: 'Phone', type: 'text', required: true, group: 'Student' },
            { name: 'email', label: 'Email', type: 'text', group: 'Student' },
            { name: 'courseInterest', label: 'Course interest', type: 'text', group: 'Student' },
            { name: 'counsellor', label: 'Counsellor', type: 'reference', refModel: 'Counsellor', refLabelField: 'name', group: 'Session' },
            {
                name: 'type',
                label: 'Type',
                type: 'select',
                options: ['career', 'college', 'course', 'loan', 'general'],
                required: true,
                group: 'Session',
            },
            { name: 'mode', label: 'Mode', type: 'text', group: 'Session' },
            { name: 'scheduledAt', label: 'Scheduled at', type: 'datetime', group: 'Session' },
            { name: 'durationMinutes', label: 'Duration (minutes)', type: 'number', group: 'Session' },
            { name: 'meetingLink', label: 'Meeting link', type: 'text', group: 'Session', colSpan: 2 },
            {
                name: 'status',
                label: 'Status',
                type: 'select',
                options: ['requested', 'confirmed', 'rescheduled', 'completed', 'cancelled', 'no_show'],
                required: true,
                group: 'Workflow',
            },
            { name: 'followUpAt', label: 'Follow-up at', type: 'datetime', group: 'Workflow' },
            { name: 'internalNotes', label: 'Internal notes', type: 'textarea', group: 'Workflow', colSpan: 2 },
            { name: 'studentSummary', label: 'Summary shared with student', type: 'textarea', group: 'Workflow', colSpan: 2 },
            { name: 'cancellationReason', label: 'Cancellation reason', type: 'text', group: 'Workflow', colSpan: 2 },
        ],
    },

    leads: {
        key: 'leads',
        model: 'Lead',
        label: 'Leads',
        labelSingular: 'Lead',
        icon: 'Users',
        description: 'Every enquiry captured across the platform.',
        titleField: 'name',
        searchFields: ['name', 'phone', 'email', 'reference'],
        defaultSort: { createdAt: -1 },
        softDelete: true,
        permissions: {
            read: 'lead.read',
            create: 'lead.create',
            update: 'lead.update',
            delete: 'lead.delete',
        },
        columns: [
            { name: 'reference', label: 'Ref' },
            { name: 'name', label: 'Name' },
            { name: 'phone', label: 'Phone' },
            { name: 'source', label: 'Source', type: 'badge' },
            { name: 'assignedToName', label: 'Counsellor' },
            { name: 'status', label: 'Status', type: 'badge' },
            { name: 'createdAt', label: 'Received', type: 'date' },
        ],
        fields: [
            { name: 'name', label: 'Name', type: 'text', required: true, group: 'Contact' },
            { name: 'phone', label: 'Phone', type: 'text', required: true, group: 'Contact' },
            { name: 'email', label: 'Email', type: 'text', group: 'Contact' },
            { name: 'stateName', label: 'State', type: 'text', group: 'Contact' },
            { name: 'cityName', label: 'City', type: 'text', group: 'Contact' },
            { name: 'courseInterestName', label: 'Course interest', type: 'text', group: 'Interest' },
            { name: 'collegeInterestName', label: 'College interest', type: 'text', group: 'Interest' },
            { name: 'examInterestName', label: 'Exam interest', type: 'text', group: 'Interest' },
            { name: 'message', label: 'Message', type: 'textarea', group: 'Interest', colSpan: 2 },
            { name: 'source', label: 'Source', type: 'select', options: LEAD_SOURCES, required: true, group: 'Workflow' },
            { name: 'status', label: 'Status', type: 'select', options: LEAD_STATUSES, required: true, group: 'Workflow' },
            { name: 'priority', label: 'Priority', type: 'select', options: LEAD_PRIORITIES, required: true, group: 'Workflow' },
            { name: 'assignedTo', label: 'Assigned counsellor', type: 'reference', refModel: 'Counsellor', refLabelField: 'name', group: 'Workflow' },
            { name: 'followUpAt', label: 'Follow-up date', type: 'datetime', group: 'Workflow' },
            { name: 'lostReason', label: 'Lost reason', type: 'text', group: 'Workflow', colSpan: 2 },
        ],
    },
};

export const ADMIN_RESOURCE_KEYS = Object.keys(ADMIN_RESOURCES);

export function getAdminResource(key: string): AdminResource | undefined {
    return ADMIN_RESOURCES[key];
}
