import {
    Activity,
    Apple,
    Award,
    BadgeCheck,
    BarChart3,
    BellRing,
    Book,
    BookMarked,
    BookOpen,
    BookOpenCheck,
    Bookmark,
    Briefcase,
    Building2,
    Calculator,
    CalendarCheck,
    CalendarDays,
    Check,
    CheckCircle2,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    CircleCheck,
    CircleHelp,
    ClipboardList,
    Clock,
    Code2,
    Cog,
    Compass,
    CreditCard,
    Database,
    Download,
    ExternalLink,
    Eye,
    FileCheck,
    FileStack,
    FileText,
    Filter,
    Flame,
    Gauge,
    GitCompare,
    Globe,
    GraduationCap,
    Headphones,
    Heart,
    HeartPulse,
    HelpCircle,
    Home,
    IndianRupee,
    Info,
    Landmark,
    LayoutDashboard,
    LayoutGrid,
    Lightbulb,
    Link2,
    ListChecks,
    Loader2,
    Lock,
    LogOut,
    Mail,
    Map,
    MapPin,
    Megaphone,
    MessageCircle,
    Newspaper,
    Palette,
    Pencil,
    Phone,
    Pill,
    Play,
    Plus,
    Route,
    Scale,
    Search,
    Send,
    Settings,
    Share2,
    Shield,
    ShieldCheck,
    Smartphone,
    Sparkles,
    Star,
    Stethoscope,
    Target,
    Trash2,
    TrendingUp,
    Trophy,
    Upload,
    UserCheck,
    UserPlus,
    Users,
    Video,
    Wallet,
    X,
    type LucideIcon,
} from 'lucide-react';
import { cn } from '@/lib/utils';

/**
 * Curated icon registry.
 * Icon names come from MongoDB (categories, nav items, CMS cards) so they must be
 * resolved through an allow-list rather than a dynamic import of the whole library.
 */
export const ICONS: Record<string, LucideIcon> = {
    Activity,
    Apple,
    Award,
    BadgeCheck,
    BarChart3,
    BellRing,
    Book,
    BookMarked,
    BookOpen,
    BookOpenCheck,
    Bookmark,
    Briefcase,
    Building2,
    Calculator,
    CalendarCheck,
    CalendarDays,
    Check,
    CheckCircle2,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    CircleCheck,
    CircleHelp,
    ClipboardList,
    Clock,
    Code2,
    Cog,
    Compass,
    CreditCard,
    Database,
    Download,
    ExternalLink,
    Eye,
    FileCheck,
    FileStack,
    FileText,
    Filter,
    Flame,
    Gauge,
    GitCompare,
    Globe,
    GraduationCap,
    Headphones,
    Heart,
    HeartPulse,
    HelpCircle,
    Home,
    IndianRupee,
    Info,
    Landmark,
    LayoutDashboard,
    LayoutGrid,
    Lightbulb,
    Link2,
    ListChecks,
    Loader2,
    Lock,
    LogOut,
    Mail,
    Map,
    MapPin,
    Megaphone,
    MessageCircle,
    Newspaper,
    Palette,
    Pencil,
    Phone,
    Pill,
    Play,
    Plus,
    Route,
    Scale,
    Search,
    Send,
    Settings,
    Share2,
    Shield,
    ShieldCheck,
    Smartphone,
    Sparkles,
    Star,
    Stethoscope,
    Target,
    Trash2,
    TrendingUp,
    Trophy,
    Upload,
    UserCheck,
    UserPlus,
    Users,
    Video,
    Wallet,
    X,
};

export const ICON_NAMES = Object.keys(ICONS);

interface IconProps {
    name?: string;
    className?: string;
    strokeWidth?: number;
    fallback?: keyof typeof ICONS;
    'aria-hidden'?: boolean;
}

export function Icon({
    name,
    className,
    strokeWidth = 2,
    fallback = 'GraduationCap',
    ...rest
}: IconProps) {
    const Component = (name && ICONS[name]) || ICONS[fallback];
    return (
        <Component
            className={cn('h-4 w-4 shrink-0', className)}
            strokeWidth={strokeWidth}
            aria-hidden
            {...rest}
        />
    );
}
